"""empty message

Revision ID: 32131eb42266
Revises: 45027a2fe97b
Create Date: 2021-07-02 00:28:49.121083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32131eb42266'
down_revision = '45027a2fe97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
