"""empty message

Revision ID: 98ade78211b6
Revises: 14ab363b75c2
Create Date: 2021-06-22 23:42:28.611175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ade78211b6'
down_revision = '14ab363b75c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete_it',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lol', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delete_it')
    # ### end Alembic commands ###
